---
name: "Check and Lint Repo"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.sh"
      - ".github/workflows/*.yml"
      - "Dockerfile"

jobs:
  check:
    name: Check and Lint Repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project â¬‡ï¸
        uses: actions/checkout@v4

      - name: Run ShellCheck ğŸš
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2086

      - name: Lint Dockerfile ğŸ‹
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: Dockerfile
